"""Adiciona campo descricao

Revision ID: 5bbf5aba4e8f
Revises: 64848c16344d
Create Date: 2025-10-07 20:55:26.204134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbf5aba4e8f'
down_revision = '64848c16344d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('loja', sa.String(length=100), nullable=True),
    sa.Column('link_afiliado', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ofertas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('imagem', sa.TEXT(), nullable=True),
    sa.Column('preco', sa.TEXT(), nullable=True),
    sa.Column('link_afiliado', sa.TEXT(), nullable=True),
    sa.Column('loja', sa.TEXT(), nullable=True),
    sa.Column('categoria', sa.TEXT(), nullable=True),
    sa.Column('destaque', sa.BOOLEAN(), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('oferta')
    # ### end Alembic commands ###
