"""Criar tabela ofertas

Revision ID: 64848c16344d
Revises: 
Create Date: 2025-10-07 19:25:58.556962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64848c16344d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('imagem', sa.Text(), nullable=True),
    sa.Column('preco', sa.Text(), nullable=True),
    sa.Column('link_afiliado', sa.Text(), nullable=True),
    sa.Column('loja', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas')
    # ### end Alembic commands ###
