"""Adiciona campo categoria_id em Oferta

Revision ID: a9b32f8f9299
Revises: e96362b0744d
Create Date: 2025-10-20 23:22:05.238779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b32f8f9299'
down_revision = 'e96362b0744d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
