"""Adiciona campo senha_hash

Revision ID: ab5fefe532c6
Revises: 35f790fd1c70
Create Date: 2025-10-09 20:48:10.028793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5fefe532c6'
down_revision = '35f790fd1c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
