"""cria tabela favoritos corretamente

Revision ID: bc0b3f16c0e8
Revises: ab5fefe532c6
Create Date: 2025-10-13 21:28:49.569285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0b3f16c0e8'
down_revision = 'ab5fefe532c6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('favoritos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('oferta_id', sa.Integer(), nullable=False),
        sa.Column('data_favorito', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id']),
        sa.ForeignKeyConstraint(['oferta_id'], ['oferta.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('autor_id', sa.INTEGER(), nullable=False),
    sa.Column('oferta_id', sa.INTEGER(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=255), nullable=True),
    sa.Column('loja', sa.VARCHAR(length=100), nullable=True),
    sa.Column('link_afiliado', sa.VARCHAR(length=255), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=True),
    sa.Column('destaque', sa.BOOLEAN(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('senha_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###
