"""Cria ou atualiza tabela oferta

Revision ID: e96362b0744d
Revises: bc0b3f16c0e8
Create Date: 2025-10-20 22:21:27.308985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96362b0744d'
down_revision = 'bc0b3f16c0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
